site_name: Cloud Cost Handbook
site_url: http://handbook.vantage.sh
theme:
  name: material
  features:
    - navigation.sections
  logo: assets/logo.svg
  icon:
    repo: fontawesome/brands/github-square
  favicon: assets/logo.svg
  custom_dir: overrides

extra:
  generator: false

extra_css:
  - stylesheets/extra.css

repo_name: vantage-sh/handbook
repo_url: https://github.com/vantage-sh/handbook

markdown_extensions:
  - attr_list
  - toc:
      permalink: "#"
  - admonition
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

nav:
  - 'Overview' : 'index.md'
  - 'General Concepts': 
    - 'Regions' : 'aws/concepts/regions.md'
    - 'Credits': 'aws/concepts/credits.md'
    - 'Rightsizing': 'aws/concepts/rightsizing.md'
    - 'Savings Plans' : 'aws/concepts/savings-plans.md'
    - 'Reserved Instances' : 'aws/concepts/reserved-instances.md'
    - 'Tags': 'aws/concepts/tags.md'

  - 'AWS Services':
    - 'CloudFront': 'aws/services/cloudfront-pricing.md'
    - 'CloudWatch': 'aws/services/cloudwatch-pricing.md'
    - 'DynamoDB': 'aws/services/dynamodb-pricing.md'
    - 'EBS': 'aws/services/ebs-pricing.md'
    - 'EC2': 'aws/services/ec2-pricing.md'
    - 'EC2-Other': 'aws/services/ec2-other-pricing.md'
    - 'ECS & Fargate': 'aws/services/ecs-and-fargate-pricing.md'
    - 'ECR': 'aws/services/ecr-pricing.md'
    - 'ELB': 'aws/services/elb-pricing.md'
    - 'ElastiCache': 'aws/services/elasticache-pricing.md'
    - 'ElasticSearch': 'aws/services/elasticsearch-pricing.md'
    - 'Lambda': 'aws/services/lambda-pricing.md'
    - 'RDS': 'aws/services/rds-pricing.md'
    - 'Route 53': 'aws/services/route-53-pricing.md'
    - 'S3': 'aws/services/s3-pricing.md'
    - 'VPC': 'aws/services/vpc-pricing.md'
    - 'WorkSpaces': 'aws/services/workspaces-pricing.md'
    

google_analytics:
  - G-TEYTN5V029
  - auto
